"""
Leak-free Scikit-Learn preprocessing pipelines for clinical tabular data.
"""

from typing import List, Optional
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler, RobustScaler

from src.heart_risk.config import Config, load_config
from src.heart_risk.features.engineering import ClinicalFeatureEngineer


def create_preprocessing_pipeline(
    config: Optional[Config] = None,
    use_feature_engineering: bool = True,
    scaler_type: str = "standard",
) -> Pipeline:
    """Construct an end-to-end, leak-free preprocessing pipeline.

    Args:
        config: Optional Config instance.
        use_feature_engineering: Whether to prepend domain feature engineering.
        scaler_type: "standard" for StandardScaler or "robust" for RobustScaler.

    Returns:
        Configured Scikit-Learn Pipeline.
    """
    if config is None:
        config = load_config()

    base_num_cols = list(config.data.numerical_features)
    cat_cols = list(config.data.categorical_features)

    # Derived numerical columns added by ClinicalFeatureEngineer
    derived_num_cols = []
    if use_feature_engineering and config.data.feature_engineering.enabled:
        fe = config.data.feature_engineering
        if fe.add_pulse_pressure:
            derived_num_cols.append("pulse_pressure")
        if fe.add_hr_reserve_ratio:
            derived_num_cols.append("hr_reserve_ratio")
        if fe.add_chol_age_ratio:
            derived_num_cols.append("chol_age_ratio")
        if fe.add_exercise_risk_index:
            derived_num_cols.append("exercise_risk_index")

    all_num_cols = base_num_cols + derived_num_cols

    scaler = RobustScaler() if scaler_type == "robust" else StandardScaler()

    num_transformer = Pipeline(
        steps=[
            ("scaler", scaler),
        ]
    )

    # In modern scikit-learn, sparse_output is preferred over sparse
    try:
        cat_encoder = OneHotEncoder(
            handle_unknown="ignore", sparse_output=False
        )
    except TypeError:
        cat_encoder = OneHotEncoder(handle_unknown="ignore", sparse=False)

    cat_transformer = Pipeline(
        steps=[
            ("onehot", cat_encoder),
        ]
    )

    column_transformer = ColumnTransformer(
        transformers=[
            ("num", num_transformer, all_num_cols),
            ("cat", cat_transformer, cat_cols),
        ],
        remainder="drop",
        verbose_feature_names_out=False,
    )

    if use_feature_engineering and config.data.feature_engineering.enabled:
        pipeline = Pipeline(
            steps=[
                ("feature_engineer", ClinicalFeatureEngineer()),
                ("preprocessor", column_transformer),
            ]
        )
    else:
        pipeline = Pipeline(
            steps=[
                ("preprocessor", column_transformer),
            ]
        )

    return pipeline


def get_feature_names_after_preprocessing(
    pipeline: Pipeline,
    sample_df: pd.DataFrame,
) -> List[str]:
    """Extract names of all features generated by the preprocessing pipeline.

    Args:
        pipeline: Fitted or unfitted preprocessing pipeline.
        sample_df: Sample DataFrame to fit/transform.

    Returns:
        List of output feature name strings.
    """
    if not hasattr(pipeline, "named_steps"):
        return []

    # If pipeline is not fitted yet, fit on sample
    try:
        if "feature_engineer" in pipeline.named_steps:
            df_fe = pipeline.named_steps["feature_engineer"].fit_transform(
                sample_df
            )
        else:
            df_fe = sample_df

        preprocessor = pipeline.named_steps["preprocessor"]
        if not hasattr(preprocessor, "transformers_"):
            preprocessor.fit(df_fe)

        if hasattr(preprocessor, "get_feature_names_out"):
            return list(preprocessor.get_feature_names_out())
    except Exception:
        pass

    # Fallback to numeric + categorical placeholder names
    return [f"feature_{i}" for i in range(sample_df.shape[1])]
